---
  - name: Create groups
    group:
      name: "{{ item.name }}"
      state: present
      gid: "{{ item.gid }}"
    loop: "{{ create_groups }}"
  #- name: Set root password
  #  user:
  #    name: root
  #    password: "{{ root_pw }}"
  #  when: root_pw is defined
  - name: Create users
    user:
      name: "{{ item.name }}"
      password: "{{ item.password }}"
      uid: "{{ item.uid }}"
      group: "{{ item.group }}"
      groups: "{{ item.groups }}"
      append: "{{ item.append }}"
      shell: "{{ item.shell }}"
    loop: "{{ create_users }}"